using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum NotePitch
{
    Rest = -1,
    G9	= 127,
    Gb9 = 126,
    F9	= 125,
    E9	= 124,
    Eb9 = 123,
    D9	= 122,
    Db9 = 121,
    C9	= 120,
    B8	= 119,
    Bb8 = 118,
    A8	= 117,
    Ab8 = 116,
    G8	= 115,
    Gb8 = 114,
    F8	= 113,
    E8	= 112,
    Eb8 = 111,
    D8  = 110,
    Db8 = 109,
    C8  = 108,
    B7  = 107,
    Bb7 = 106,
    A7  = 105,
    Ab7 = 104,
    G7  = 103,
    Gb7 = 102,
    F7  = 101,
    E7  = 100,
    Eb7 = 99,
    D7  = 98,
    Db7 = 97,
    C7  = 96,
    B6  = 95,
    Bb6 = 94,
    A6  = 93,
    Ab6 = 92,
    G6  = 91,
    Gb6 = 90,
    F6  = 89,
    E6  = 88,
    Eb6 = 87,
    D6  = 86,
    Db6 = 85,
    C6  = 84,
    B5  = 83,
    Bb5 = 82,
    A5  = 81,
    Ab5 = 80,
    G5  = 79,
    Gb5 = 78,
    F5  = 77,
    E5  = 76,
    Eb5 = 75,
    D5  = 74,
    Db5 = 73,
    C5  = 72,
    B4  = 71,
    Bb4 = 70,
    A4  = 69,
    Ab4 = 68,
    G4  = 67,
    Gb4 = 66,
    F4  = 65,
    E4  = 64,
    Eb4 = 63,
    D4  = 62,
    Db4 = 61,
    C4  = 60,
    B3  = 59,
    Bb3 = 58,
    A3  = 57,
    Ab3 = 56,
    G3  = 55,
    Gb3 = 54,
    F3  = 53,
    E3  = 52,
    Eb3 = 51,
    D3  = 50,
    Db3 = 49,
    C3  = 48,
    B2  = 47,
    Bb2 = 46,
    A2  = 45,
    Ab2 = 44,
    G2  = 43,
    Gb2 = 42,
    F2  = 41,
    E2  = 40,
    Eb2 = 39,
    D2  = 38,
    Db2 = 37,
    C2  = 36,
    B1  = 35,
    Bb1 = 34,
    A1  = 33,
    Ab1 = 32,
    G1  = 31,
    Gb1 = 30,
    F1  = 29,
    E1  = 28,
    Eb1 = 27,
    D1  = 26,
    Db1 = 25,
    C1  = 24,
    B0  = 23,
    Bb0 = 22,
    A0  = 21,
}

public enum NoteName
{
    Ab,
    G,
    Gb,
    F,
    E,
    Eb,
    D,
    Db,
    C,
    B,
    Bb,
    A
}

public static class NotePitchExtensions
{
    public static NoteName Name(this NotePitch pitch) => pitch switch
    {
        NotePitch.G9 => NoteName.G,
        NotePitch.Gb9 => NoteName.Gb,
        NotePitch.F9 => NoteName.F,
        NotePitch.E9 => NoteName.E,
        NotePitch.Eb9 => NoteName.Eb,
        NotePitch.D9 => NoteName.D,
        NotePitch.Db9 => NoteName.Db,
        NotePitch.C9 => NoteName.C,
        NotePitch.B8 => NoteName.B,
        NotePitch.Bb8 => NoteName.Bb,
        NotePitch.A8 => NoteName.A,
        NotePitch.Ab8 => NoteName.Ab,
        NotePitch.G8 => NoteName.G,
        NotePitch.Gb8 => NoteName.Gb,
        NotePitch.F8 => NoteName.F,
        NotePitch.E8 => NoteName.E,
        NotePitch.Eb8 => NoteName.Eb,
        NotePitch.D8 => NoteName.D,
        NotePitch.Db8 => NoteName.Db,
        NotePitch.C8 => NoteName.C,
        NotePitch.B7 => NoteName.B,
        NotePitch.Bb7 => NoteName.Bb,
        NotePitch.A7 => NoteName.A,
        NotePitch.Ab7 => NoteName.Ab,
        NotePitch.G7 => NoteName.G,
        NotePitch.Gb7 => NoteName.Gb,
        NotePitch.F7 => NoteName.F,
        NotePitch.E7 => NoteName.E,
        NotePitch.Eb7 => NoteName.Eb,
        NotePitch.D7 => NoteName.D,
        NotePitch.Db7 => NoteName.Db,
        NotePitch.C7 => NoteName.C,
        NotePitch.B6 => NoteName.B,
        NotePitch.Bb6 => NoteName.Bb,
        NotePitch.A6 => NoteName.A,
        NotePitch.Ab6 => NoteName.Ab,
        NotePitch.G6 => NoteName.G,
        NotePitch.Gb6 => NoteName.Gb,
        NotePitch.F6 => NoteName.F,
        NotePitch.E6 => NoteName.E,
        NotePitch.Eb6 => NoteName.Eb,
        NotePitch.D6 => NoteName.D,
        NotePitch.Db6 => NoteName.Db,
        NotePitch.C6 => NoteName.C,
        NotePitch.B5 => NoteName.B,
        NotePitch.Bb5 => NoteName.Bb,
        NotePitch.A5 => NoteName.A,
        NotePitch.Ab5 => NoteName.Ab,
        NotePitch.G5 => NoteName.G,
        NotePitch.Gb5 => NoteName.Gb,
        NotePitch.F5 => NoteName.F,
        NotePitch.E5 => NoteName.E,
        NotePitch.Eb5 => NoteName.Eb,
        NotePitch.D5 => NoteName.D,
        NotePitch.Db5 => NoteName.Db,
        NotePitch.C5 => NoteName.C,
        NotePitch.B4 => NoteName.B,
        NotePitch.Bb4 => NoteName.Bb,
        NotePitch.A4 => NoteName.A,
        NotePitch.Ab4 => NoteName.Ab,
        NotePitch.G4 => NoteName.G,
        NotePitch.Gb4 => NoteName.Gb,
        NotePitch.F4 => NoteName.F,
        NotePitch.E4 => NoteName.E,
        NotePitch.Eb4 => NoteName.Eb,
        NotePitch.D4 => NoteName.D,
        NotePitch.Db4 => NoteName.Db,
        NotePitch.C4 => NoteName.C,
        NotePitch.B3 => NoteName.B,
        NotePitch.Bb3 => NoteName.Bb,
        NotePitch.A3 => NoteName.A,
        NotePitch.Ab3 => NoteName.Ab,
        NotePitch.G3 => NoteName.G,
        NotePitch.Gb3 => NoteName.Gb,
        NotePitch.F3 => NoteName.F,
        NotePitch.E3 => NoteName.E,
        NotePitch.Eb3 => NoteName.Eb,
        NotePitch.D3 => NoteName.D,
        NotePitch.Db3 => NoteName.Db,
        NotePitch.C3 => NoteName.C,
        NotePitch.B2 => NoteName.B,
        NotePitch.Bb2 => NoteName.Bb,
        NotePitch.A2 => NoteName.A,
        NotePitch.Ab2 => NoteName.Ab,
        NotePitch.G2 => NoteName.G,
        NotePitch.Gb2 => NoteName.Gb,
        NotePitch.F2 => NoteName.F,
        NotePitch.E2 => NoteName.E,
        NotePitch.Eb2 => NoteName.Eb,
        NotePitch.D2 => NoteName.D,
        NotePitch.Db2 => NoteName.Db,
        NotePitch.C2 => NoteName.C,
        NotePitch.B1 => NoteName.B,
        NotePitch.Bb1 => NoteName.Bb,
        NotePitch.A1 => NoteName.A,
        NotePitch.Ab1 => NoteName.Ab,
        NotePitch.G1 => NoteName.G,
        NotePitch.Gb1 => NoteName.Gb,
        NotePitch.F1 => NoteName.F,
        NotePitch.E1 => NoteName.E,
        NotePitch.Eb1 => NoteName.Eb,
        NotePitch.D1 => NoteName.D,
        NotePitch.Db1 => NoteName.Db,
        NotePitch.C1 => NoteName.C,
        NotePitch.B0 => NoteName.B,
        NotePitch.Bb0 => NoteName.Bb,
        NotePitch.A0 => NoteName.A,
        _ => throw new System.Exception("Note does not have a name!")
    };
}
